name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Получить код
        uses: actions/checkout@v3

      - name: Проверка
        run: echo "Проект работает"

      - name: Деплой
        run: echo "Deploy completed"

